from tortoise.models import Model
from tortoise import fields

class shield_machine(Model):
    id = fields.IntField(pk=True, index=True)
    connect_key = fields.CharField(max_length=255, description="盾构机编号", null=True)
    ring = fields.IntField(description="施工环号", null=True)
    sub_code = fields.CharField(max_length=255, description="施工区间编码", null=True)
    sub_name = fields.CharField(max_length=255, description="施工区间名称", null=True)
    digging_diameter = fields.CharField(max_length=255, description="盾构机开挖直径", null=True)
    total_length = fields.CharField(max_length=255, description="盾构机总长", null=True)
    total_weight = fields.CharField(max_length=255, description="盾构机总重", null=True)
    design_pressure = fields.CharField(max_length=255, description="盾构机设计压力", null=True)
    working_pressure = fields.CharField(max_length=255, description="盾构机工作压力", null=True)
    max_thrust = fields.CharField(max_length=255, description="盾构机最大推力", null=True)
    max_cutter_speed = fields.CharField(max_length=255, description="盾构机最大刀盘转速", null=True)
    DP_XZNJ = fields.CharField(max_length=255, description="刀盘旋转扭矩", null=True)
    DP_SDNJ = fields.CharField(max_length=255, description="刀盘扭矩", null=True)
    DP_KKL = fields.CharField(max_length=255, description="刀盘开口率", null=True)
    max_advance_speed = fields.CharField(max_length=255, description="最大推进速度", null=True)
    cylinder_layout = fields.CharField(max_length=255, description="油缸布置形式", null=True)
    shield_type = fields.CharField(max_length=255, description="盾构机类型", null=True)
    construction_loc = fields.CharField(max_length=255, description="项目施工位置", null=True)
    start_end_section = fields.CharField(max_length=255, description="起始区间、走向", null=True)
    ring_segment_size = fields.CharField(max_length=255, description="每环尺寸", null=True)
    tail_brush_count = fields.CharField(max_length=255, description="盾尾刷道数", null=True)
    tail_gap = fields.CharField(max_length=255, description="盾尾间隙", null=True)
    grease_pressure = fields.CharField(max_length=255, description="油脂压力", null=True)
    yzcs = fields.CharField(max_length=255, description="油脂参数", null=True)
    gd_cc = fields.CharField(max_length=255, description="管道尺寸", null=True)
    gd_sl = fields.CharField(max_length=255, description="管道数量", null=True)
    jy_ls = fields.CharField(max_length=255, description="浆液流速", null=True)
    jy_nd = fields.CharField(max_length=255, description="浆液浓度", null=True)
    cz_ll = fields.CharField(max_length=255, description="出渣粒径", null=True)
    jb_psxs = fields.CharField(max_length=255, description="搅拌破碎形式", null=True)
    flushing_nozzle_quantity = fields.CharField(max_length=255, description="冲洗喷嘴数量", null=True)
    flushing_nozzle_type = fields.CharField(max_length=255, description="冲洗喷嘴形式", null=True)
    flushing_flow = fields.CharField(max_length=255, description="冲洗流量", null=True)
    property_unit = fields.CharField(max_length=255, description="产权单位", null=True)
    project_status = fields.CharField(max_length=255, description="项目状态", null=True)
    equipment_property = fields.CharField(max_length=255, description="设备性质", null=True)
    equipment_brand = fields.CharField(max_length=255, description="设备品牌", null=True)
    segment_outside_diameter = fields.CharField(max_length=255, description="管片外径", null=True)
    segment_width = fields.CharField(max_length=255, description="管片宽度", null=True)
    manufacturer = fields.CharField(max_length=255, description="生产厂家", null=True)

    class Meta:
        table = "shield_machine"
        default_connection = "ecust_ddg_conn"